name: Build Android APK

on:
  push:
    branches:
      - main  # Triggers the action on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openjdk-11-jdk
          yes | sdkmanager "platforms;android-31" "platform-tools" "build-tools;31.0.0" "cmdline-tools;latest"

      - name: Build the APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3  # Updated version here
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
